#+title: Armin Hofmann Graphic Design Manual Summer Project
#+author: Ashley Sagar


* WHAT EVEN IS THIS PROJECT?

This is my self imposed summer project to work through the Armin
Hofman Graphic Design Manual to try and give myself some grounding in graphic design. I will be making all of the work in the Processing app and also porting some work over to P5 so I  can build a web portfolio alongside this.

I will attempt to add in programming techniques along the way by going back over the workshops in creative coding 1 class I had whilst in my first term studying my MFA in Computational Arts at Goldsmiths University.

I will work through the examples and make them availiable on a Patreon whilst sharing my own creations on my [[https://www.instagram.com/green.road.studios/][green.road.studios]]



* Things to do
- [X] make a github
- [ ] load images and pde files into git


* 2023_07_05
- [ ] start on sketch 26
  How to approach sketch 26??

  - [ ] make the original sketch

  - [ ] make shapes into classes?

  - [ ] maybe make 1 black square which is devided into 9 equal parts and each white block is randomly assigned??


* 2023_07_10
- [X] its now the 10th and Ive done nothing.

  
- [X] OK. sketch 26

- [X] make the sketch as dfrawn

- [X] upoload the last sketch 25 to the gitblog
  
- [X] upload sketch 26 to blog

- [ ] upload to github

* TODO 2023_07_11

- [ ] image 26
- [ ] figure out a way to randomise white blocks onto the balck squares? 
- [ ] make one black square class
- [ ] make a randomly appearing white square(s) appear on the black square class
  - [ ] 9 white squares at 100x100px
  - [ ] they all randomly appear with alpha at either 0 of 255
  - [ ] 
  - 

* TODO 

